workflows:
  ios-native-workflow:
    name: GameApp
    max_build_duration: 120
    instance_type: mac_mini_m1
    working_directory: GameApp
    environment:
      vars:
        BUNDLE_ID: "hadi.GameApp"
        XCODE_PROJECT: "GameApp.xcodeproj" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "GameApp" # <-- Put the name of your Xcode scheme here
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/GameApp/$XCODE_PROJECT" \
            --scheme "GameApp/$XCODE_SCHEME"
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
